name: Send updata_os to poweroff

on:
  workflow_dispatch:

env:
  BE_UID: ${{ secrets.BE_UID }}
  BE_URL: https://push.bemfa.com/
  TOPIC: poweroff
  MSG: updata_os
  TYPE: text

jobs:
  send_bemfa:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Bemfa
        run: |
          set -euo pipefail
          encoded_msg=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${MSG}'))")
          url="${BE_URL}${BE_UID}?topic=${TOPIC}&type=${TYPE}&msg=${encoded_msg}"
          echo "Sending Bemfa message to $url"
          resp=$(curl -sS "$url" || echo "Bemfa send failed")
          echo "Bemfa response: $resp"
