name: notify
permissions:
  contents: write
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}
jobs:
  check_and_notify:
    runs-on: ubuntu-latest
    env:
      BE_UID: ${{ secrets.BE_UID }}
      BE_URL: ${{ secrets.BE_URL }}
      REMOTE_URL: ${{ secrets.REMOTE_URL }}
      TOPIC: poweroff
      MSG: update_os
      TYPE: '3'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch remote file and compute hash
        id: check
        run: |
          set -euo pipefail
          curl -sS "${REMOTE_URL}" -o remote_os.c
          sha=$(sha256sum remote_os.c | awk '{print $1}')
          prev=""
          if [ -f last_hash.txt ]; then
            prev=$(cat last_hash.txt | tr -d '[:space:]')
          fi
          echo "remote_sha=$sha" >> $GITHUB_OUTPUT
          echo "prev_sha=$prev" >> $GITHUB_OUTPUT

      - name: Compare and act if changed
        if: steps.check.outputs.remote_sha != steps.check.outputs.prev_sha
        run: |
          set -euo pipefail
          url="${BE_URL}${BE_UID}&topic=${TOPIC}&type=${TYPE}&msg=${MSG}"
          curl -sS "$url" -o /tmp/bemfa_resp.txt || echo "Bemfa send failed"
          sha=$(sha256sum remote_os.c | awk '{print $1}')
          echo "$sha" > last_hash.txt
          cp remote_os.c last_remote_os.c
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_hash.txt last_remote_os.c
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "update hash"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${GITHUB_REF#refs/heads/}
          fi

      - name: No change - exit
        if: steps.check.outputs.remote_sha == steps.check.outputs.prev_sha
        run: echo "No change detected"
