name: encrypt-and-send

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  encrypt-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl python3-pip
          pip install pycryptodome

      - name: Get token
        env:
          BE_POST: ${{ secrets.BE_POST }}
          BE_HOST: ${{ secrets.BE_HOST }}
          BE_CT: ${{ secrets.BE_CT }}
          BE_UA: ${{ secrets.BE_UA }}
          BE_BODY: ${{ secrets.BE_BODY }}
        run: |
          echo "1️⃣ 获取 Bemfa token…"
          export TOKEN=$(curl -sS -X POST "$BE_POST" \
            -H "$BE_HOST" \
            -H "$BE_CT" \
            -H "$BE_UA" \
            -d "$BE_BODY" \
            | jq -r '.data.token')
          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "❌ 获取 token 失败！"
            exit 1
          fi
          echo "✅ token 获取成功: $TOKEN"

      - name: Encrypt token and write t.c
        env:
          BE_K: ${{ secrets.BE_K }}
          BE_V: ${{ secrets.BE_V }}
        run: python3 - <<'EOF'
import os, base64
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad

key = bytes.fromhex(os.environ['BE_K'])
iv = bytes.fromhex(os.environ['BE_V'])
token = os.environ['TOKEN']

cipher = AES.new(key, AES.MODE_CBC, iv)
enc = cipher.encrypt(pad(token.encode(), AES.block_size))

with open("t.c", "w") as f:
    f.write(base64.b64encode(enc).decode())

print("✅ 已写入 t.c")
EOF

      - name: Commit encrypted token
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add t.c
          git commit -m "Update encrypted token [skip ci]" || echo "No changes"
          git push
